sudo: required
language: clojure
jdk:
  - oraclejdk8
lein: 2.8.1
addons:
  chrome: stable
before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - npm install karma karma-cljs-test karma-chrome-launcher
  - npm install -g karma-cli
script:
  - lein do clean, test, doo chrome-headless test once, cloverage --coveralls
  - curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'
