language: clojure
jdk:
  - oraclejdk8
lein: 2.7.1
script:
  - lein cloverage --coveralls --ns-exclude-regex user
  - curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'
